FROM python:3.11
LABEL maintainer="d@example.com"
WORKDIR /app

COPY requirements.txt .
RUN pip install --upgrade pip -r requirements.txt

COPY . .

EXPOSE 81
CMD ["uvicorn", "app_docker_A:app", "--port", "81", "--host", "0.0.0.0"]
